services:

  mysql:
    image: mysql:8.0
    container_name: food-ordering-mysql
    restart: "no"

    environment:
      MYSQL_DATABASE: food_app
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: food-ordering-backend
    restart: "no"

    depends_on:
      mysql:
        condition: service_healthy

    ports:
      - "8081:8081"

    environment:
      DB_URL: jdbc:mysql://mysql:3306/food_app
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}

volumes:
  mysql_data: